name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    steps:
      - name: Check secrets loaded
        run:
          'echo "TOKEN LENGTH: ${#RAILWAY_TOKEN}"'
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - name: Deploy
        run: railway up --service=${{ env.SVC_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          SVC_ID: 1421d26c-2477-4294-8fdf-32e417902a63
